export interface N8nIntegration {
  name: string;
  displayName: string;
  icon: string;
  category: "communication" | "crm" | "marketing" | "project" | "storage" | "database" | "dev" | "ai" | "finance" | "analytics" | "social" | "other";
  popular: boolean;
}

export const N8N_INTEGRATIONS: N8nIntegration[] = [
  { name: "ActionNetwork", displayName: "Action Network", icon: "📢", category: "marketing", popular: false },
  { name: "ActiveCampaign", displayName: "ActiveCampaign", icon: "📧", category: "marketing", popular: true },
  { name: "AcuityScheduling", displayName: "Acuity Scheduling", icon: "📅", category: "other", popular: false },
  { name: "Adalo", displayName: "Adalo", icon: "📱", category: "other", popular: false },
  { name: "Affinity", displayName: "Affinity", icon: "🤝", category: "crm", popular: false },
  { name: "AgileCrm", displayName: "Agile CRM", icon: "🤝", category: "crm", popular: false },
  { name: "AiTransform", displayName: "AI Transform", icon: "🤖", category: "ai", popular: false },
  { name: "Airtable", displayName: "Airtable", icon: "📊", category: "database", popular: true },
  { name: "Airtop", displayName: "Airtop", icon: "🌐", category: "other", popular: false },
  { name: "Amqp", displayName: "AMQP", icon: "📨", category: "dev", popular: false },
  { name: "ApiTemplateIo", displayName: "API Template.io", icon: "📝", category: "dev", popular: false },
  { name: "Asana", displayName: "Asana", icon: "✅", category: "project", popular: true },
  { name: "Autopilot", displayName: "Autopilot", icon: "✈️", category: "marketing", popular: false },
  { name: "Aws", displayName: "AWS", icon: "☁️", category: "dev", popular: true },
  { name: "BambooHr", displayName: "BambooHR", icon: "🎋", category: "other", popular: false },
  { name: "Bannerbear", displayName: "Bannerbear", icon: "🐻", category: "other", popular: false },
  { name: "Baserow", displayName: "Baserow", icon: "📊", category: "database", popular: false },
  { name: "Beeminder", displayName: "Beeminder", icon: "🐝", category: "other", popular: false },
  { name: "Bitbucket", displayName: "Bitbucket", icon: "🪣", category: "dev", popular: true },
  { name: "Bitly", displayName: "Bitly", icon: "🔗", category: "marketing", popular: false },
  { name: "Bitwarden", displayName: "Bitwarden", icon: "🔒", category: "other", popular: false },
  { name: "Box", displayName: "Box", icon: "📦", category: "storage", popular: true },
  { name: "Brandfetch", displayName: "Brandfetch", icon: "🏷️", category: "other", popular: false },
  { name: "Brevo", displayName: "Brevo", icon: "📨", category: "marketing", popular: true },
  { name: "Bubble", displayName: "Bubble", icon: "🫧", category: "other", popular: false },
  { name: "Cal", displayName: "Cal.com", icon: "📅", category: "other", popular: false },
  { name: "Calendly", displayName: "Calendly", icon: "📅", category: "other", popular: true },
  { name: "Chargebee", displayName: "Chargebee", icon: "💳", category: "finance", popular: false },
  { name: "CircleCi", displayName: "CircleCI", icon: "⭕", category: "dev", popular: false },
  { name: "Cisco", displayName: "Cisco", icon: "🌐", category: "dev", popular: false },
  { name: "Clearbit", displayName: "Clearbit", icon: "🔍", category: "analytics", popular: false },
  { name: "ClickUp", displayName: "ClickUp", icon: "☑️", category: "project", popular: false },
  { name: "Clockify", displayName: "Clockify", icon: "⏰", category: "project", popular: false },
  { name: "Cloudflare", displayName: "Cloudflare", icon: "☁️", category: "dev", popular: true },
  { name: "Cockpit", displayName: "Cockpit CMS", icon: "🛩️", category: "other", popular: false },
  { name: "Coda", displayName: "Coda", icon: "📄", category: "project", popular: false },
  { name: "Code", displayName: "Code", icon: "💻", category: "dev", popular: false },
  { name: "CoinGecko", displayName: "CoinGecko", icon: "🦎", category: "finance", popular: false },
  { name: "CompareDatasets", displayName: "Compare Datasets", icon: "🔀", category: "other", popular: false },
  { name: "Compression", displayName: "Compression", icon: "🗜️", category: "other", popular: false },
  { name: "Contentful", displayName: "Contentful", icon: "📝", category: "other", popular: false },
  { name: "ConvertKit", displayName: "ConvertKit", icon: "📧", category: "marketing", popular: true },
  { name: "Copper", displayName: "Copper", icon: "🪙", category: "crm", popular: false },
  { name: "Cortex", displayName: "Cortex XSOAR", icon: "🧠", category: "other", popular: false },
  { name: "CrateDb", displayName: "CrateDB", icon: "🗄️", category: "database", popular: false },
  { name: "Cron", displayName: "Cron", icon: "⏰", category: "dev", popular: false },
  { name: "Crypto", displayName: "Crypto", icon: "🔐", category: "dev", popular: false },
  { name: "Currents", displayName: "Currents", icon: "⚡", category: "other", popular: false },
  { name: "CustomerIo", displayName: "Customer.io", icon: "👤", category: "marketing", popular: true },
  { name: "DataTable", displayName: "Data Table", icon: "📊", category: "other", popular: false },
  { name: "Databricks", displayName: "Databricks", icon: "🔬", category: "database", popular: true },
  { name: "DateTime", displayName: "Date & Time", icon: "🕐", category: "other", popular: false },
  { name: "DebugHelper", displayName: "Debug Helper", icon: "🐛", category: "dev", popular: false },
  { name: "DeepL", displayName: "DeepL", icon: "🌐", category: "ai", popular: false },
  { name: "Demio", displayName: "Demio", icon: "🎥", category: "marketing", popular: false },
  { name: "Dhl", displayName: "DHL", icon: "📦", category: "other", popular: false },
  { name: "Discord", displayName: "Discord", icon: "💬", category: "communication", popular: true },
  { name: "Discourse", displayName: "Discourse", icon: "💬", category: "social", popular: false },
  { name: "Disqus", displayName: "Disqus", icon: "💬", category: "social", popular: false },
  { name: "Drift", displayName: "Drift", icon: "💬", category: "crm", popular: false },
  { name: "Dropbox", displayName: "Dropbox", icon: "📁", category: "storage", popular: true },
  { name: "Dropcontact", displayName: "Dropcontact", icon: "📧", category: "crm", popular: false },
  { name: "DynamicCredentialCheck", displayName: "Dynamic Credential Check", icon: "🔑", category: "dev", popular: false },
  { name: "E2eTest", displayName: "E2E Test", icon: "🧪", category: "dev", popular: false },
  { name: "ERPNext", displayName: "ERPNext", icon: "📋", category: "other", popular: false },
  { name: "EditImage", displayName: "Edit Image", icon: "🖼️", category: "other", popular: false },
  { name: "Egoi", displayName: "E-goi", icon: "📧", category: "marketing", popular: false },
  { name: "Elastic", displayName: "Elasticsearch", icon: "🔍", category: "database", popular: false },
  { name: "EmailReadImap", displayName: "Email Read (IMAP)", icon: "📥", category: "communication", popular: false },
  { name: "EmailSend", displayName: "Send Email", icon: "📤", category: "communication", popular: false },
  { name: "Emelia", displayName: "Emelia", icon: "📧", category: "marketing", popular: false },
  { name: "ErrorTrigger", displayName: "Error Trigger", icon: "🚨", category: "dev", popular: false },
  { name: "Evaluation", displayName: "Evaluation", icon: "✅", category: "other", popular: false },
  { name: "Eventbrite", displayName: "Eventbrite", icon: "🎫", category: "marketing", popular: false },
  { name: "ExecuteCommand", displayName: "Execute Command", icon: "🖥️", category: "dev", popular: false },
  { name: "ExecuteWorkflow", displayName: "Execute Workflow", icon: "⚙️", category: "dev", popular: false },
  { name: "ExecutionData", displayName: "Execution Data", icon: "📊", category: "other", popular: false },
  { name: "Facebook", displayName: "Facebook", icon: "📘", category: "social", popular: false },
  { name: "FacebookLeadAds", displayName: "Facebook Lead Ads", icon: "📘", category: "marketing", popular: false },
  { name: "Figma", displayName: "Figma", icon: "🎨", category: "other", popular: false },
  { name: "FileMaker", displayName: "FileMaker", icon: "📁", category: "database", popular: false },
  { name: "Files", displayName: "Files", icon: "📄", category: "other", popular: false },
  { name: "Filter", displayName: "Filter", icon: "🔽", category: "other", popular: false },
  { name: "Flow", displayName: "Flow", icon: "🔀", category: "other", popular: false },
  { name: "Form", displayName: "Form Trigger", icon: "📋", category: "other", popular: false },
  { name: "FormIo", displayName: "Form.io", icon: "📋", category: "other", popular: false },
  { name: "Formstack", displayName: "Formstack", icon: "📋", category: "other", popular: false },
  { name: "Freshdesk", displayName: "Freshdesk", icon: "🎫", category: "crm", popular: true },
  { name: "Freshservice", displayName: "Freshservice", icon: "🎫", category: "other", popular: false },
  { name: "FreshworksCrm", displayName: "Freshworks CRM", icon: "🤝", category: "crm", popular: false },
  { name: "Ftp", displayName: "FTP", icon: "📂", category: "dev", popular: true },
  { name: "Function", displayName: "Function", icon: "ƒ", category: "dev", popular: false },
  { name: "FunctionItem", displayName: "Function Item", icon: "ƒ", category: "dev", popular: false },
  { name: "GetResponse", displayName: "GetResponse", icon: "📧", category: "marketing", popular: false },
  { name: "Ghost", displayName: "Ghost", icon: "👻", category: "other", popular: false },
  { name: "Git", displayName: "Git", icon: "🔀", category: "dev", popular: false },
  { name: "Github", displayName: "GitHub", icon: "🐙", category: "dev", popular: true },
  { name: "Gitlab", displayName: "GitLab", icon: "🦊", category: "dev", popular: true },
  { name: "GoToWebinar", displayName: "GoToWebinar", icon: "🎥", category: "marketing", popular: false },
  { name: "Gong", displayName: "Gong", icon: "📞", category: "crm", popular: false },
  { name: "Google", displayName: "Google", icon: "🔍", category: "other", popular: false },
  { name: "Gotify", displayName: "Gotify", icon: "🔔", category: "communication", popular: false },
  { name: "Grafana", displayName: "Grafana", icon: "📊", category: "analytics", popular: false },
  { name: "GraphQL", displayName: "GraphQL", icon: "🔗", category: "dev", popular: true },
  { name: "Grist", displayName: "Grist", icon: "📊", category: "database", popular: false },
  { name: "Gumroad", displayName: "Gumroad", icon: "🛒", category: "finance", popular: false },
  { name: "HackerNews", displayName: "Hacker News", icon: "🔶", category: "social", popular: false },
  { name: "HaloPSA", displayName: "HaloPSA", icon: "😇", category: "crm", popular: false },
  { name: "Harvest", displayName: "Harvest", icon: "🌾", category: "finance", popular: false },
  { name: "HelpScout", displayName: "Help Scout", icon: "🎯", category: "crm", popular: false },
  { name: "HighLevel", displayName: "HighLevel", icon: "📈", category: "crm", popular: false },
  { name: "HomeAssistant", displayName: "Home Assistant", icon: "🏠", category: "other", popular: false },
  { name: "Html", displayName: "HTML", icon: "🌐", category: "dev", popular: false },
  { name: "HtmlExtract", displayName: "HTML Extract", icon: "🌐", category: "dev", popular: false },
  { name: "HttpRequest", displayName: "HTTP Request", icon: "🌐", category: "dev", popular: true },
  { name: "Hubspot", displayName: "HubSpot", icon: "🟠", category: "crm", popular: true },
  { name: "HumanticAI", displayName: "Humantic AI", icon: "🤖", category: "ai", popular: false },
  { name: "Hunter", displayName: "Hunter", icon: "🎯", category: "crm", popular: false },
  { name: "ICalendar", displayName: "iCalendar", icon: "📅", category: "other", popular: false },
  { name: "If", displayName: "If", icon: "🔀", category: "other", popular: false },
  { name: "Intercom", displayName: "Intercom", icon: "💬", category: "crm", popular: true },
  { name: "Interval", displayName: "Interval", icon: "⏱️", category: "other", popular: false },
  { name: "InvoiceNinja", displayName: "Invoice Ninja", icon: "💰", category: "finance", popular: false },
  { name: "ItemLists", displayName: "Item Lists", icon: "📋", category: "other", popular: false },
  { name: "Iterable", displayName: "Iterable", icon: "📧", category: "marketing", popular: false },
  { name: "Jenkins", displayName: "Jenkins", icon: "🔧", category: "dev", popular: false },
  { name: "JinaAI", displayName: "Jina AI", icon: "🤖", category: "ai", popular: false },
  { name: "Jira", displayName: "Jira", icon: "🎯", category: "project", popular: true },
  { name: "JotForm", displayName: "Jotform", icon: "📋", category: "other", popular: false },
  { name: "Jwt", displayName: "JWT", icon: "🔐", category: "dev", popular: false },
  { name: "Kafka", displayName: "Apache Kafka", icon: "📨", category: "dev", popular: true },
  { name: "Keap", displayName: "Keap", icon: "🤝", category: "crm", popular: false },
  { name: "KoBoToolbox", displayName: "KoBoToolbox", icon: "📋", category: "other", popular: false },
  { name: "Ldap", displayName: "LDAP", icon: "🔑", category: "dev", popular: false },
  { name: "Lemlist", displayName: "Lemlist", icon: "📧", category: "marketing", popular: false },
  { name: "Line", displayName: "LINE", icon: "💚", category: "communication", popular: false },
  { name: "Linear", displayName: "Linear", icon: "📐", category: "project", popular: true },
  { name: "LingvaNex", displayName: "LingvaNex", icon: "🌐", category: "ai", popular: false },
  { name: "LinkedIn", displayName: "LinkedIn", icon: "💼", category: "social", popular: true },
  { name: "LocalFileTrigger", displayName: "Local File Trigger", icon: "📁", category: "dev", popular: false },
  { name: "LoneScale", displayName: "LoneScale", icon: "📊", category: "other", popular: false },
  { name: "MQTT", displayName: "MQTT", icon: "📨", category: "dev", popular: true },
  { name: "Magento", displayName: "Magento", icon: "🛒", category: "other", popular: false },
  { name: "Mailcheck", displayName: "Mailcheck", icon: "✅", category: "communication", popular: false },
  { name: "Mailchimp", displayName: "Mailchimp", icon: "🐵", category: "marketing", popular: true },
  { name: "MailerLite", displayName: "MailerLite", icon: "📧", category: "marketing", popular: false },
  { name: "Mailgun", displayName: "Mailgun", icon: "🔫", category: "communication", popular: false },
  { name: "Mailjet", displayName: "Mailjet", icon: "✈️", category: "communication", popular: false },
  { name: "Mandrill", displayName: "Mandrill", icon: "🐵", category: "communication", popular: false },
  { name: "ManualTrigger", displayName: "Manual Trigger", icon: "👆", category: "other", popular: false },
  { name: "Markdown", displayName: "Markdown", icon: "📝", category: "other", popular: false },
  { name: "Marketstack", displayName: "Marketstack", icon: "📈", category: "finance", popular: false },
  { name: "Matrix", displayName: "Matrix", icon: "💬", category: "communication", popular: false },
  { name: "Mattermost", displayName: "Mattermost", icon: "💬", category: "communication", popular: false },
  { name: "Mautic", displayName: "Mautic", icon: "📧", category: "marketing", popular: false },
  { name: "Medium", displayName: "Medium", icon: "✍️", category: "social", popular: false },
  { name: "Merge", displayName: "Merge", icon: "🔗", category: "other", popular: false },
  { name: "MessageAnAgent", displayName: "Message an Agent", icon: "💬", category: "communication", popular: false },
  { name: "MessageBird", displayName: "MessageBird", icon: "🐦", category: "communication", popular: false },
  { name: "Metabase", displayName: "Metabase", icon: "📊", category: "analytics", popular: false },
  { name: "Microsoft", displayName: "Microsoft", icon: "🪟", category: "other", popular: false },
  { name: "Mindee", displayName: "Mindee", icon: "🔍", category: "ai", popular: false },
  { name: "Misp", displayName: "MISP", icon: "🛡️", category: "other", popular: false },
  { name: "MistralAI", displayName: "Mistral AI", icon: "🤖", category: "ai", popular: false },
  { name: "Mocean", displayName: "Mocean", icon: "🌊", category: "communication", popular: false },
  { name: "MondayCom", displayName: "Monday.com", icon: "📋", category: "project", popular: false },
  { name: "MongoDb", displayName: "MongoDB", icon: "🍃", category: "database", popular: true },
  { name: "MonicaCrm", displayName: "Monica CRM", icon: "🤝", category: "crm", popular: false },
  { name: "MoveBinaryData", displayName: "Move Binary Data", icon: "📦", category: "other", popular: false },
  { name: "Msg91", displayName: "MSG91", icon: "📱", category: "communication", popular: false },
  { name: "MySql", displayName: "MySQL", icon: "🐬", category: "database", popular: true },
  { name: "N8n", displayName: "n8n", icon: "⚡", category: "dev", popular: false },
  { name: "N8nTrainingCustomerDatastore", displayName: "n8n Training: Customer Datastore", icon: "📚", category: "other", popular: false },
  { name: "N8nTrainingCustomerMessenger", displayName: "n8n Training: Customer Messenger", icon: "📚", category: "other", popular: false },
  { name: "N8nTrigger", displayName: "n8n Trigger", icon: "⚡", category: "dev", popular: false },
  { name: "Nasa", displayName: "NASA", icon: "🚀", category: "other", popular: false },
  { name: "Netlify", displayName: "Netlify", icon: "🌐", category: "dev", popular: true },
  { name: "Netscaler", displayName: "NetScaler", icon: "🌐", category: "dev", popular: false },
  { name: "NextCloud", displayName: "Nextcloud", icon: "☁️", category: "storage", popular: false },
  { name: "NoOp", displayName: "No Operation", icon: "⏸️", category: "other", popular: false },
  { name: "NocoDB", displayName: "NocoDB", icon: "📊", category: "database", popular: false },
  { name: "Notion", displayName: "Notion", icon: "📝", category: "project", popular: true },
  { name: "Npm", displayName: "npm", icon: "📦", category: "dev", popular: false },
  { name: "Odoo", displayName: "Odoo", icon: "📦", category: "crm", popular: false },
  { name: "Okta", displayName: "Okta", icon: "🔐", category: "dev", popular: false },
  { name: "OneSimpleApi", displayName: "One Simple API", icon: "🌐", category: "other", popular: false },
  { name: "Onfleet", displayName: "Onfleet", icon: "🚚", category: "other", popular: false },
  { name: "OpenAi", displayName: "OpenAI", icon: "🤖", category: "ai", popular: true },
  { name: "OpenThesaurus", displayName: "OpenThesaurus", icon: "📖", category: "other", popular: false },
  { name: "OpenWeatherMap", displayName: "OpenWeatherMap", icon: "🌤️", category: "other", popular: false },
  { name: "Oracle", displayName: "Oracle", icon: "🗄️", category: "database", popular: false },
  { name: "Orbit", displayName: "Orbit", icon: "🪐", category: "other", popular: false },
  { name: "Oura", displayName: "Oura", icon: "💍", category: "other", popular: false },
  { name: "Paddle", displayName: "Paddle", icon: "🏓", category: "finance", popular: false },
  { name: "PagerDuty", displayName: "PagerDuty", icon: "📟", category: "other", popular: true },
  { name: "PayPal", displayName: "PayPal", icon: "💰", category: "finance", popular: false },
  { name: "Peekalink", displayName: "Peekalink", icon: "🔗", category: "other", popular: false },
  { name: "Perplexity", displayName: "Perplexity", icon: "🔍", category: "ai", popular: false },
  { name: "Phantombuster", displayName: "PhantomBuster", icon: "👻", category: "other", popular: false },
  { name: "PhilipsHue", displayName: "Philips Hue", icon: "💡", category: "other", popular: false },
  { name: "Pipedrive", displayName: "Pipedrive", icon: "🔄", category: "crm", popular: false },
  { name: "Plivo", displayName: "Plivo", icon: "📱", category: "communication", popular: false },
  { name: "PostBin", displayName: "PostBin", icon: "📮", category: "dev", popular: false },
  { name: "PostHog", displayName: "PostHog", icon: "🦔", category: "analytics", popular: true },
  { name: "Postgres", displayName: "PostgreSQL", icon: "🐘", category: "database", popular: true },
  { name: "Postmark", displayName: "Postmark", icon: "📮", category: "communication", popular: false },
  { name: "ProfitWell", displayName: "ProfitWell", icon: "📈", category: "analytics", popular: false },
  { name: "Pushbullet", displayName: "Pushbullet", icon: "📱", category: "communication", popular: false },
  { name: "Pushcut", displayName: "Pushcut", icon: "🔔", category: "communication", popular: false },
  { name: "Pushover", displayName: "Pushover", icon: "🔔", category: "communication", popular: false },
  { name: "QuestDb", displayName: "QuestDB", icon: "🗄️", category: "database", popular: false },
  { name: "QuickBase", displayName: "Quick Base", icon: "⚡", category: "database", popular: false },
  { name: "QuickBooks", displayName: "QuickBooks", icon: "💰", category: "finance", popular: false },
  { name: "QuickChart", displayName: "QuickChart", icon: "📊", category: "other", popular: false },
  { name: "RabbitMQ", displayName: "RabbitMQ", icon: "🐰", category: "dev", popular: true },
  { name: "Raindrop", displayName: "Raindrop.io", icon: "🌧️", category: "other", popular: false },
  { name: "ReadBinaryFile", displayName: "Read Binary File", icon: "📄", category: "dev", popular: false },
  { name: "ReadBinaryFiles", displayName: "Read Binary Files", icon: "📄", category: "dev", popular: false },
  { name: "ReadPdf", displayName: "Read PDF", icon: "📄", category: "other", popular: false },
  { name: "Reddit", displayName: "Reddit", icon: "🤖", category: "social", popular: true },
  { name: "Redis", displayName: "Redis", icon: "🔴", category: "database", popular: true },
  { name: "RenameKeys", displayName: "Rename Keys", icon: "✏️", category: "other", popular: false },
  { name: "RespondToWebhook", displayName: "Respond to Webhook", icon: "🌐", category: "dev", popular: false },
  { name: "Rocketchat", displayName: "Rocket.Chat", icon: "💬", category: "communication", popular: false },
  { name: "RssFeedRead", displayName: "RSS Feed Read", icon: "📡", category: "other", popular: false },
  { name: "Rundeck", displayName: "Rundeck", icon: "🔧", category: "dev", popular: false },
  { name: "S3", displayName: "AWS S3", icon: "🪣", category: "storage", popular: false },
  { name: "Salesforce", displayName: "Salesforce", icon: "☁️", category: "crm", popular: true },
  { name: "Salesmate", displayName: "Salesmate", icon: "🤝", category: "crm", popular: false },
  { name: "Schedule", displayName: "Schedule Trigger", icon: "⏰", category: "other", popular: false },
  { name: "SeaTable", displayName: "SeaTable", icon: "📊", category: "database", popular: false },
  { name: "SecurityScorecard", displayName: "SecurityScorecard", icon: "🛡️", category: "other", popular: false },
  { name: "Segment", displayName: "Segment", icon: "📊", category: "analytics", popular: true },
  { name: "SendGrid", displayName: "SendGrid", icon: "📧", category: "communication", popular: true },
  { name: "Sendy", displayName: "Sendy", icon: "📧", category: "marketing", popular: false },
  { name: "SentryIo", displayName: "Sentry", icon: "🚨", category: "dev", popular: true },
  { name: "ServiceNow", displayName: "ServiceNow", icon: "🎫", category: "other", popular: false },
  { name: "Set", displayName: "Set", icon: "✏️", category: "other", popular: false },
  { name: "Shopify", displayName: "Shopify", icon: "🛒", category: "other", popular: true },
  { name: "Signl4", displayName: "SIGNL4", icon: "🚨", category: "communication", popular: false },
  { name: "Simulate", displayName: "Simulate", icon: "🧪", category: "dev", popular: false },
  { name: "Slack", displayName: "Slack", icon: "💬", category: "communication", popular: true },
  { name: "Sms77", displayName: "SMS77", icon: "📱", category: "communication", popular: false },
  { name: "Snowflake", displayName: "Snowflake", icon: "❄️", category: "database", popular: true },
  { name: "SplitInBatches", displayName: "Split In Batches", icon: "📦", category: "other", popular: false },
  { name: "Splunk", displayName: "Splunk", icon: "📊", category: "analytics", popular: false },
  { name: "Spotify", displayName: "Spotify", icon: "🎵", category: "other", popular: false },
  { name: "SpreadsheetFile", displayName: "Spreadsheet File", icon: "📊", category: "other", popular: false },
  { name: "SseTrigger", displayName: "SSE Trigger", icon: "🌐", category: "dev", popular: false },
  { name: "Ssh", displayName: "SSH", icon: "🔑", category: "dev", popular: true },
  { name: "Stackby", displayName: "Stackby", icon: "📊", category: "database", popular: false },
  { name: "StickyNote", displayName: "Sticky Note", icon: "📝", category: "other", popular: false },
  { name: "StopAndError", displayName: "Stop and Error", icon: "🛑", category: "dev", popular: false },
  { name: "Storyblok", displayName: "Storyblok", icon: "📝", category: "other", popular: false },
  { name: "Strapi", displayName: "Strapi", icon: "📝", category: "other", popular: false },
  { name: "Strava", displayName: "Strava", icon: "🏃", category: "other", popular: false },
  { name: "Stripe", displayName: "Stripe", icon: "💳", category: "finance", popular: true },
  { name: "Supabase", displayName: "Supabase", icon: "⚡", category: "database", popular: true },
  { name: "SurveyMonkey", displayName: "SurveyMonkey", icon: "🐵", category: "other", popular: false },
  { name: "Switch", displayName: "Switch", icon: "🔀", category: "other", popular: false },
  { name: "SyncroMSP", displayName: "SyncroMSP", icon: "🔄", category: "other", popular: false },
  { name: "Taiga", displayName: "Taiga", icon: "🏔️", category: "project", popular: false },
  { name: "Tapfiliate", displayName: "Tapfiliate", icon: "🔗", category: "marketing", popular: false },
  { name: "Telegram", displayName: "Telegram", icon: "✈️", category: "communication", popular: true },
  { name: "TheHive", displayName: "TheHive", icon: "🐝", category: "other", popular: false },
  { name: "TheHiveProject", displayName: "TheHive Project", icon: "🐝", category: "other", popular: false },
  { name: "TimeSaved", displayName: "Time Saved", icon: "⏱️", category: "other", popular: false },
  { name: "TimescaleDb", displayName: "TimescaleDB", icon: "⏰", category: "database", popular: false },
  { name: "Todoist", displayName: "Todoist", icon: "✅", category: "project", popular: false },
  { name: "Toggl", displayName: "Toggl", icon: "⏱️", category: "project", popular: false },
  { name: "Totp", displayName: "TOTP", icon: "🔐", category: "dev", popular: false },
  { name: "Transform", displayName: "Transform", icon: "🔄", category: "other", popular: false },
  { name: "TravisCi", displayName: "Travis CI", icon: "🔧", category: "dev", popular: false },
  { name: "Trello", displayName: "Trello", icon: "📋", category: "project", popular: true },
  { name: "Twake", displayName: "Twake", icon: "💬", category: "communication", popular: false },
  { name: "Twilio", displayName: "Twilio", icon: "📱", category: "communication", popular: true },
  { name: "Twist", displayName: "Twist", icon: "💬", category: "communication", popular: false },
  { name: "Twitter", displayName: "Twitter/X", icon: "🐦", category: "social", popular: true },
  { name: "Typeform", displayName: "Typeform", icon: "📋", category: "other", popular: false },
  { name: "UProc", displayName: "UProc", icon: "🔍", category: "other", popular: false },
  { name: "UnleashedSoftware", displayName: "Unleashed Software", icon: "📦", category: "other", popular: false },
  { name: "Uplead", displayName: "UpLead", icon: "🔍", category: "crm", popular: false },
  { name: "UptimeRobot", displayName: "Uptime Robot", icon: "🤖", category: "other", popular: false },
  { name: "UrlScanIo", displayName: "URLScan.io", icon: "🔍", category: "other", popular: false },
  { name: "Venafi", displayName: "Venafi", icon: "🔐", category: "other", popular: false },
  { name: "Vero", displayName: "Vero", icon: "📧", category: "marketing", popular: false },
  { name: "Vonage", displayName: "Vonage", icon: "📱", category: "communication", popular: false },
  { name: "Wait", displayName: "Wait", icon: "⏳", category: "other", popular: false },
  { name: "Webflow", displayName: "Webflow", icon: "🌐", category: "other", popular: false },
  { name: "Webhook", displayName: "Webhook", icon: "🌐", category: "dev", popular: false },
  { name: "Wekan", displayName: "Wekan", icon: "📋", category: "project", popular: false },
  { name: "WhatsApp", displayName: "WhatsApp", icon: "💬", category: "communication", popular: false },
  { name: "Wise", displayName: "Wise", icon: "💸", category: "finance", popular: false },
  { name: "WooCommerce", displayName: "WooCommerce", icon: "🛒", category: "other", popular: true },
  { name: "Wordpress", displayName: "WordPress", icon: "📝", category: "other", popular: true },
  { name: "Workable", displayName: "Workable", icon: "💼", category: "other", popular: false },
  { name: "WorkflowTrigger", displayName: "Workflow Trigger", icon: "⚡", category: "dev", popular: false },
  { name: "WriteBinaryFile", displayName: "Write Binary File", icon: "📄", category: "dev", popular: false },
  { name: "Wufoo", displayName: "Wufoo", icon: "📋", category: "other", popular: false },
  { name: "Xero", displayName: "Xero", icon: "💰", category: "finance", popular: false },
  { name: "Xml", displayName: "XML", icon: "📄", category: "other", popular: false },
  { name: "Yourls", displayName: "YOURLS", icon: "🔗", category: "other", popular: false },
  { name: "Zammad", displayName: "Zammad", icon: "🎫", category: "crm", popular: false },
  { name: "Zendesk", displayName: "Zendesk", icon: "🎫", category: "crm", popular: true },
  { name: "Zoho", displayName: "Zoho", icon: "📦", category: "crm", popular: false },
  { name: "Zoom", displayName: "Zoom", icon: "📹", category: "communication", popular: true },
  { name: "Zulip", displayName: "Zulip", icon: "💬", category: "communication", popular: false },
];
