// Real n8n node types from https://github.com/n8n-io/n8n/
// 437 node types extracted from packages/nodes-base/nodes/

export interface N8nNodeType {
  type: string;
  name: string;
  displayName: string;
  description: string;
  category: string;
  icon: string;
}

export const N8N_NODE_TYPES: N8nNodeType[] = [
  { type: "n8n-nodes-base.jinaAi", name: "jinaAi", displayName: "Jina AI", description: "Interact with Jina AI API", category: "AI", icon: "🤖" },
  { type: "n8n-nodes-base.mistralAi", name: "mistralAi", displayName: "Mistral AI", description: "Consume Mistral AI API", category: "AI", icon: "🤖" },
  { type: "n8n-nodes-base.openAi", name: "openAi", displayName: "OpenAI", description: "Consume Open AI", category: "AI", icon: "🤖" },
  { type: "n8n-nodes-base.perplexity", name: "perplexity", displayName: "Perplexity", description: "AI-powered answer engine that provides accurate, trusted, and real-time answers to any question. Supports chat completions, agent responses, web search, and embeddings.", category: "AI", icon: "🤖" },
  { type: "n8n-nodes-base.googleAds", name: "googleAds", displayName: "Google Ads", description: "Use the Google Ads API", category: "Analytics", icon: "📈" },
  { type: "n8n-nodes-base.googleAnalytics", name: "googleAnalytics", displayName: "Google Analytics", description: "Use the Google Analytics API", category: "Analytics", icon: "📈" },
  { type: "n8n-nodes-base.acuitySchedulingTrigger", name: "acuitySchedulingTrigger", displayName: "Acuity Scheduling Trigger", description: "Handle Acuity Scheduling events via webhooks", category: "Calendar", icon: "📅" },
  { type: "n8n-nodes-base.calTrigger", name: "calTrigger", displayName: "Cal.com Trigger", description: "Handle Cal.com events via webhooks", category: "Calendar", icon: "📅" },
  { type: "n8n-nodes-base.calendlyTrigger", name: "calendlyTrigger", displayName: "Calendly Trigger", description: "Starts the workflow when Calendly events occur", category: "Calendar", icon: "📅" },
  { type: "n8n-nodes-base.googleCalendar", name: "googleCalendar", displayName: "Google Calendar", description: "Consume Google Calendar API", category: "Calendar", icon: "📅" },
  { type: "n8n-nodes-base.googleCalendarTrigger", name: "googleCalendarTrigger", displayName: "Google Calendar Trigger", description: "Starts the workflow when Google Calendar events occur", category: "Calendar", icon: "📅" },
  { type: "n8n-nodes-base.discord", name: "discord", displayName: "Discord", description: "Sends data to Discord", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.drift", name: "drift", displayName: "Drift", description: "Consume Drift API", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.googleChat", name: "googleChat", displayName: "Google Chat", description: "Consume Google Chat API", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.gotify", name: "gotify", displayName: "Gotify", description: "Consume Gotify API", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.intercom", name: "intercom", displayName: "Intercom", description: "Consume Intercom API", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.line", name: "line", displayName: "Line", description: "Consume Line API", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.matrix", name: "matrix", displayName: "Matrix", description: "Consume Matrix API", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.mattermost", name: "mattermost", displayName: "Mattermost", description: "Sends data to Mattermost", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.microsoftTeams", name: "microsoftTeams", displayName: "Microsoft Teams", description: "Consume Microsoft Teams API", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.microsoftTeamsTrigger", name: "microsoftTeamsTrigger", displayName: "Microsoft Teams Trigger", description: "Triggers workflows in n8n based on events from Microsoft Teams, such as new messages or team updates, using specified configurations.", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.rocketchat", name: "rocketchat", displayName: "RocketChat", description: "Consume RocketChat API", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.slack", name: "slack", displayName: "Slack", description: "Consume Slack API", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.slackTrigger", name: "slackTrigger", displayName: "Slack Trigger", description: "Handle Slack events via webhooks", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.telegram", name: "telegram", displayName: "Telegram", description: "Sends data to Telegram", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.telegramTrigger", name: "telegramTrigger", displayName: "Telegram Trigger", description: "Starts the workflow on a Telegram update", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.twake", name: "twake", displayName: "Twake", description: "Consume Twake API", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.twist", name: "twist", displayName: "Twist", description: "Consume Twist API", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.ciscoWebex", name: "ciscoWebex", displayName: "Webex by Cisco", description: "Consume the Cisco Webex API", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.ciscoWebexTrigger", name: "ciscoWebexTrigger", displayName: "Webex by Cisco Trigger", description: "Starts the workflow when Cisco Webex events occur.", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.zulip", name: "zulip", displayName: "Zulip", description: "Consume Zulip API", category: "Communication", icon: "💬" },
  { type: "n8n-nodes-base.aggregate", name: "aggregate", displayName: "Aggregate", description: "Combine a field from many items into a list in a single item", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.messageAnAgent", name: "messageAnAgent", displayName: "AI Agent V1", description: "Send a message to a n8n agent", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.aiTransform", name: "aiTransform", displayName: "AI Transform", description: "Modify data based on instructions written in plain english", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.dynamicCredentialCheck", name: "dynamicCredentialCheck", displayName: "Check Credential Status", description: "Checks whether the triggering user has the required end-user credential configured. Routes to", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.code", name: "code", displayName: "Code", description: "Run custom JavaScript or Python code", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.compareDatasets", name: "compareDatasets", displayName: "Compare Datasets", description: "Compare two inputs for changes", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.compression", name: "compression", displayName: "Compression", description: "Compress and decompress files", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.moveBinaryData", name: "moveBinaryData", displayName: "Convert to/from binary data", description: "Move data between binary and JSON properties", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.crypto", name: "crypto", displayName: "Crypto", description: "Provide cryptographic utilities", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.dataTable", name: "dataTable", displayName: "Data table", description: "Permanently save data across workflow executions in a table", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.dateTime", name: "dateTime", displayName: "Date & Time", description: "Allows you to manipulate date and time values", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.debugHelper", name: "debugHelper", displayName: "DebugHelper", description: "Causes problems intentionally and generates useful data for debugging", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.filter", name: "filter", displayName: "Filter", description: "Keep only items matching a condition", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.function", name: "function", displayName: "Function", description: "Run custom function code which gets executed once and allows you to add, remove, change and replace items", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.functionItem", name: "functionItem", displayName: "Function Item", description: "Run custom function code which gets executed once per item", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.htmlExtract", name: "htmlExtract", displayName: "HTML Extract", description: "Extracts data from HTML", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.if", name: "if", displayName: "If", description: "Route items to different branches (true/false)", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.itemLists", name: "itemLists", displayName: "Item Lists", description: "Helper for working with lists of items and transforming arrays", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.jwt", name: "jwt", displayName: "JWT", description: "Be sure to add a valid JWT token to the", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.limit", name: "limit", displayName: "Limit", description: "Restrict the number of items", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.markdown", name: "markdown", displayName: "Markdown", description: "Convert data between Markdown and HTML", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.merge", name: "merge", displayName: "Merge", description: "Merges data of multiple streams once data from both is available", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.formTrigger", name: "formTrigger", displayName: "n8n Form Trigger", description: "Generate webforms in n8n and pass their responses to the workflow", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.noOp", name: "noOp", displayName: "No Operation, do nothing", description: "No Operation", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.removeDuplicates", name: "removeDuplicates", displayName: "Remove Duplicates", description: "Delete items with matching field values", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.renameKeys", name: "renameKeys", displayName: "Rename Keys", description: "Update item field names", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.set", name: "set", displayName: "Set", description: "Add or edit fields on an input item and optionally remove other fields", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.simulate", name: "simulate", displayName: "Simulate", description: "Simulate a node", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.sort", name: "sort", displayName: "Sort", description: "Change items order", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.splitInBatches", name: "splitInBatches", displayName: "Split In Batches", description: "Split data into batches and iterate over each batch", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.splitOut", name: "splitOut", displayName: "Split Out", description: "Turn a list inside item(s) into separate items", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.spreadsheetFile", name: "spreadsheetFile", displayName: "Spreadsheet File", description: "Reads and writes data from a spreadsheet file like CSV, XLS, ODS, etc", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.stickyNote", name: "stickyNote", displayName: "Sticky Note", description: "Make your workflow easier to understand", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.stopAndError", name: "stopAndError", displayName: "Stop and Error", description: "Throw an error in the workflow", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.summarize", name: "summarize", displayName: "Summarize", description: "Sum, count, max, etc. across items", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.switch", name: "switch", displayName: "Switch", description: "Route items depending on defined expression or rules", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.totp", name: "totp", displayName: "TOTP", description: "Generate a time-based one-time password", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.timeSaved", name: "timeSaved", displayName: "Track Time Saved", description: "Dynamically track time saved based on the workflow’s execution path and the number of items processed", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.xml", name: "xml", displayName: "XML", description: "Convert data from and to XML", category: "Core", icon: "⚙️" },
  { type: "n8n-nodes-base.activeCampaign", name: "activeCampaign", displayName: "ActiveCampaign", description: "Create and edit data in ActiveCampaign", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.activeCampaignTrigger", name: "activeCampaignTrigger", displayName: "ActiveCampaign Trigger", description: "Handle ActiveCampaign events via webhooks", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.affinity", name: "affinity", displayName: "Affinity", description: "Consume Affinity API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.affinityTrigger", name: "affinityTrigger", displayName: "Affinity Trigger", description: "Handle Affinity events via webhooks", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.agileCrm", name: "agileCrm", displayName: "Agile CRM", description: "Consume Agile CRM API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.copper", name: "copper", displayName: "Copper", description: "Consume the Copper API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.copperTrigger", name: "copperTrigger", displayName: "Copper Trigger", description: "Handle Copper events via webhooks", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.demio", name: "demio", displayName: "Demio", description: "Consume the Demio API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.dropcontact", name: "dropcontact", displayName: "Dropcontact", description: "Find B2B emails and enrich contacts", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.freshworksCrm", name: "freshworksCrm", displayName: "Freshworks CRM", description: "Consume the Freshworks CRM API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.highLevel", name: "highLevel", displayName: "HighLevel", description: "Consume HighLevel API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.hubspot", name: "hubspot", displayName: "HubSpot", description: "Consume HubSpot API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.hubspotTrigger", name: "hubspotTrigger", displayName: "HubSpot Trigger", description: "Starts the workflow when HubSpot events occur", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.humanticAi", name: "humanticAi", displayName: "Humantic AI", description: "Consume Humantic AI API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.hunter", name: "hunter", displayName: "Hunter", description: "Consume Hunter API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.keap", name: "keap", displayName: "Keap", description: "Consume Keap API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.keapTrigger", name: "keapTrigger", displayName: "Keap Trigger", description: "Starts the workflow when Infusionsoft events occur", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.monicaCrm", name: "monicaCrm", displayName: "Monica CRM", description: "Consume the Monica CRM API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.pipedrive", name: "pipedrive", displayName: "Pipedrive", description: "Create and edit data in Pipedrive", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.salesforce", name: "salesforce", displayName: "Salesforce", description: "Consume Salesforce API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.salesforceTrigger", name: "salesforceTrigger", displayName: "Salesforce Trigger", description: "Fetches data from Salesforce and starts the workflow on specified polling intervals.", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.salesmate", name: "salesmate", displayName: "Salesmate", description: "Consume Salesmate API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.uplead", name: "uplead", displayName: "Uplead", description: "Consume Uplead API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.zohoCrm", name: "zohoCrm", displayName: "Zoho CRM", description: "Consume Zoho CRM API", category: "CRM", icon: "💼" },
  { type: "n8n-nodes-base.airtable", name: "airtable", displayName: "Airtable", description: "Read, update, write and delete data from Airtable", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.airtableTrigger", name: "airtableTrigger", displayName: "Airtable Trigger", description: "Starts the workflow when Airtable events occur", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.awsDynamoDb", name: "awsDynamoDb", displayName: "AWS DynamoDB", description: "Consume the AWS DynamoDB API", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.azureCosmosDb", name: "azureCosmosDb", displayName: "Azure Cosmos DB", description: "Interact with Azure Cosmos DB API", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.baserow", name: "baserow", displayName: "Baserow", description: "Consume the Baserow API", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.crateDb", name: "crateDb", displayName: "CrateDB", description: "Add and update data in CrateDB", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.databricks", name: "databricks", displayName: "Databricks", description: "Interact with Databricks API", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.elasticsearch", name: "elasticsearch", displayName: "Elasticsearch", description: "Consume the Elasticsearch API", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.googleBigQuery", name: "googleBigQuery", displayName: "Google BigQuery", description: "Consume Google BigQuery API", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.googleSheets", name: "googleSheets", displayName: "Google Sheets", description: "Read, update and write data to Google Sheets", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.grafana", name: "grafana", displayName: "Grafana", description: "Consume the Grafana API", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.grist", name: "grist", displayName: "Grist", description: "Consume the Grist API", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.metabase", name: "metabase", displayName: "Metabase", description: "Use the Metabase API", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.microsoftExcel", name: "microsoftExcel", displayName: "Microsoft Excel (OneDrive)", description: "Consume the Microsoft Excel API for workbooks stored in OneDrive", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.microsoftExcelSharePoint", name: "microsoftExcelSharePoint", displayName: "Microsoft Excel (SharePoint)", description: "Read and write Excel workbooks stored in SharePoint document libraries", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.microsoftSql", name: "microsoftSql", displayName: "Microsoft SQL", description: "Get, add and update data in Microsoft SQL", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.mongoDb", name: "mongoDb", displayName: "MongoDB", description: "Find, insert and update documents in MongoDB", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.mySql", name: "mySql", displayName: "MySQL", description: "Get, add and update data in MySQL", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.nocoDb", name: "nocoDb", displayName: "NocoDB", description: "Read, update, write and delete data from NocoDB", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.postgres", name: "postgres", displayName: "Postgres", description: "Get, add and update data in Postgres", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.postgresTrigger", name: "postgresTrigger", displayName: "Postgres Trigger", description: "Listens to Postgres messages", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.questDb", name: "questDb", displayName: "QuestDB", description: "Get, add and update data in QuestDB", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.redis", name: "redis", displayName: "Redis", description: "Get, send and update data in Redis", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.redisTrigger", name: "redisTrigger", displayName: "Redis Trigger", description: "Subscribe to redis channel", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.seaTable", name: "seaTable", displayName: "SeaTable", description: "Read, update, write and delete data from SeaTable", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.seaTableTrigger", name: "seaTableTrigger", displayName: "SeaTable Trigger", description: "Starts the workflow when SeaTable events occur", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.snowflake", name: "snowflake", displayName: "Snowflake", description: "Get, add and update data in Snowflake", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.stackby", name: "stackby", displayName: "Stackby", description: "Read, write, and delete data in Stackby", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.supabase", name: "supabase", displayName: "Supabase", description: "Add, get, delete and update data in a table", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.timescaleDb", name: "timescaleDb", displayName: "TimescaleDB", description: "Add and update data in TimescaleDB", category: "Data", icon: "📊" },
  { type: "n8n-nodes-base.bitbucketTrigger", name: "bitbucketTrigger", displayName: "Bitbucket Trigger", description: "Handle Bitbucket events via webhooks", category: "Development", icon: "💻" },
  { type: "n8n-nodes-base.circleCi", name: "circleCi", displayName: "CircleCI", description: "Consume CircleCI API", category: "Development", icon: "💻" },
  { type: "n8n-nodes-base.git", name: "git", displayName: "Git", description: "Control git.", category: "Development", icon: "💻" },
  { type: "n8n-nodes-base.github", name: "github", displayName: "GitHub", description: "Consume GitHub API", category: "Development", icon: "💻" },
  { type: "n8n-nodes-base.githubTrigger", name: "githubTrigger", displayName: "Github Trigger", description: "Starts the workflow when Github events occur", category: "Development", icon: "💻" },
  { type: "n8n-nodes-base.gitlab", name: "gitlab", displayName: "GitLab", description: "Retrieve data from GitLab API", category: "Development", icon: "💻" },
  { type: "n8n-nodes-base.jenkins", name: "jenkins", displayName: "Jenkins", description: "Consume Jenkins API", category: "Development", icon: "💻" },
  { type: "n8n-nodes-base.npm", name: "npm", displayName: "Npm", description: "Consume NPM registry API", category: "Development", icon: "💻" },
  { type: "n8n-nodes-base.postHog", name: "postHog", displayName: "PostHog", description: "Consume PostHog API", category: "Development", icon: "💻" },
  { type: "n8n-nodes-base.segment", name: "segment", displayName: "Segment", description: "Consume Segment API", category: "Development", icon: "💻" },
  { type: "n8n-nodes-base.sentryIo", name: "sentryIo", displayName: "Sentry.io", description: "Consume Sentry.io API", category: "Development", icon: "💻" },
  { type: "n8n-nodes-base.travisCi", name: "travisCi", displayName: "TravisCI", description: "Consume TravisCI API", category: "Development", icon: "💻" },
  { type: "n8n-nodes-base.awsCertificateManager", name: "awsCertificateManager", displayName: "AWS Certificate Manager", description: "Sends data to AWS Certificate Manager", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.awsCognito", name: "awsCognito", displayName: "AWS Cognito", description: "Sends data to AWS Cognito", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.awsComprehend", name: "awsComprehend", displayName: "AWS Comprehend", description: "Sends data to Amazon Comprehend", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.awsElb", name: "awsElb", displayName: "AWS ELB", description: "Sends data to AWS ELB API", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.awsIam", name: "awsIam", displayName: "AWS IAM", description: "Interacts with Amazon IAM", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.awsLambda", name: "awsLambda", displayName: "AWS Lambda", description: "Invoke functions on AWS Lambda", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.awsRekognition", name: "awsRekognition", displayName: "AWS Rekognition", description: "Sends data to AWS Rekognition", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.awsSes", name: "awsSes", displayName: "AWS SES", description: "Sends data to AWS SES", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.awsSns", name: "awsSns", displayName: "AWS SNS", description: "Sends data to AWS SNS", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.awsSnsTrigger", name: "awsSnsTrigger", displayName: "AWS SNS Trigger", description: "Handle AWS SNS events via webhooks", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.awsSqs", name: "awsSqs", displayName: "AWS SQS", description: "Sends messages to AWS SQS", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.awsTextract", name: "awsTextract", displayName: "AWS Textract", description: "Sends data to Amazon Textract", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.awsTranscribe", name: "awsTranscribe", displayName: "AWS Transcribe", description: "Sends data to AWS Transcribe", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.cloudflare", name: "cloudflare", displayName: "Cloudflare", description: "Consume Cloudflare API", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.n8n", name: "n8n", displayName: "n8n", description: "Handle events and perform actions on your n8n instance", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.n8nTrigger", name: "n8nTrigger", displayName: "n8n Trigger", description: "Handle events and perform actions on your n8n instance", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.netlify", name: "netlify", displayName: "Netlify", description: "Consume Netlify API", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.netlifyTrigger", name: "netlifyTrigger", displayName: "Netlify Trigger", description: "Handle netlify events via webhooks", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.pagerDuty", name: "pagerDuty", displayName: "PagerDuty", description: "Consume PagerDuty API", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.rundeck", name: "rundeck", displayName: "Rundeck", description: "Manage Rundeck API", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.serviceNow", name: "serviceNow", displayName: "ServiceNow", description: "Consume ServiceNow API", category: "DevOps/Cloud", icon: "☁️" },
  { type: "n8n-nodes-base.contentful", name: "contentful", displayName: "Contentful", description: "Consume Contentful API", category: "Documentation/CMS", icon: "📝" },
  { type: "n8n-nodes-base.erpNext", name: "erpNext", displayName: "ERPNext", description: "Consume ERPNext API", category: "Documentation/CMS", icon: "📝" },
  { type: "n8n-nodes-base.ghost", name: "ghost", displayName: "Ghost", description: "Consume Ghost API", category: "Documentation/CMS", icon: "📝" },
  { type: "n8n-nodes-base.googleDocs", name: "googleDocs", displayName: "Google Docs", description: "Consume Google Docs API.", category: "Documentation/CMS", icon: "📝" },
  { type: "n8n-nodes-base.googleSlides", name: "googleSlides", displayName: "Google Slides", description: "Consume the Google Slides API", category: "Documentation/CMS", icon: "📝" },
  { type: "n8n-nodes-base.storyblok", name: "storyblok", displayName: "Storyblok", description: "Consume Storyblok API", category: "Documentation/CMS", icon: "📝" },
  { type: "n8n-nodes-base.strapi", name: "strapi", displayName: "Strapi", description: "Consume Strapi API", category: "Documentation/CMS", icon: "📝" },
  { type: "n8n-nodes-base.wordpress", name: "wordpress", displayName: "Wordpress", description: "Consume Wordpress API", category: "Documentation/CMS", icon: "📝" },
  { type: "n8n-nodes-base.chargebee", name: "chargebee", displayName: "Chargebee", description: "Retrieve data from Chargebee API", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.chargebeeTrigger", name: "chargebeeTrigger", displayName: "Chargebee Trigger", description: "Starts the workflow when Chargebee events occur", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.gumroadTrigger", name: "gumroadTrigger", displayName: "Gumroad Trigger", description: "Handle Gumroad events via webhooks", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.invoiceNinja", name: "invoiceNinja", displayName: "Invoice Ninja", description: "Consume Invoice Ninja API", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.invoiceNinjaTrigger", name: "invoiceNinjaTrigger", displayName: "Invoice Ninja Trigger", description: "Starts the workflow when Invoice Ninja events occur", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.magento2", name: "magento2", displayName: "Magento 2", description: "Consume Magento API", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.odoo", name: "odoo", displayName: "Odoo", description: "Consume Odoo API", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.paddle", name: "paddle", displayName: "Paddle", description: "Consume Paddle API", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.payPal", name: "payPal", displayName: "PayPal", description: "Consume PayPal API", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.payPalTrigger", name: "payPalTrigger", displayName: "PayPal Trigger", description: "Handle PayPal events via webhooks", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.quickbooks", name: "quickbooks", displayName: "QuickBooks Online", description: "Consume the QuickBooks Online API", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.shopify", name: "shopify", displayName: "Shopify", description: "Consume Shopify API", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.shopifyTrigger", name: "shopifyTrigger", displayName: "Shopify Trigger", description: "Handle Shopify events via webhooks", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.stripe", name: "stripe", displayName: "Stripe", description: "Consume the Stripe API", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.stripeTrigger", name: "stripeTrigger", displayName: "Stripe Trigger", description: "Handle Stripe events via webhooks", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.wooCommerce", name: "wooCommerce", displayName: "WooCommerce", description: "Consume WooCommerce API", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.wooCommerceTrigger", name: "wooCommerceTrigger", displayName: "WooCommerce Trigger", description: "Handle WooCommerce events via webhooks", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.xero", name: "xero", displayName: "Xero", description: "Consume Xero API", category: "E-Commerce", icon: "🛒" },
  { type: "n8n-nodes-base.sendInBlue", name: "sendInBlue", displayName: "Brevo", description: "Consume Brevo API", category: "Email", icon: "✉️" },
  { type: "n8n-nodes-base.emailReadImap", name: "emailReadImap", displayName: "Email Trigger (IMAP)", description: "Triggers the workflow when a new email is received", category: "Email", icon: "✉️" },
  { type: "n8n-nodes-base.gmail", name: "gmail", displayName: "Gmail", description: "Consume the Gmail API", category: "Email", icon: "✉️" },
  { type: "n8n-nodes-base.gmailTrigger", name: "gmailTrigger", displayName: "Gmail Trigger", description: "Fetches emails from Gmail and starts the workflow on specified polling intervals.", category: "Email", icon: "✉️" },
  { type: "n8n-nodes-base.mailgun", name: "mailgun", displayName: "Mailgun", description: "Sends an email via Mailgun", category: "Email", icon: "✉️" },
  { type: "n8n-nodes-base.mailjet", name: "mailjet", displayName: "Mailjet", description: "Consume Mailjet API", category: "Email", icon: "✉️" },
  { type: "n8n-nodes-base.mandrill", name: "mandrill", displayName: "Mandrill", description: "Consume Mandrill API", category: "Email", icon: "✉️" },
  { type: "n8n-nodes-base.microsoftOutlook", name: "microsoftOutlook", displayName: "Microsoft Outlook", description: "Consume Microsoft Outlook API", category: "Email", icon: "✉️" },
  { type: "n8n-nodes-base.microsoftOutlookTrigger", name: "microsoftOutlookTrigger", displayName: "Microsoft Outlook Trigger", description: "Fetches emails from Microsoft Outlook and starts the workflow on specified polling intervals.", category: "Email", icon: "✉️" },
  { type: "n8n-nodes-base.postmarkTrigger", name: "postmarkTrigger", displayName: "Postmark Trigger", description: "Starts the workflow when Postmark events occur", category: "Email", icon: "✉️" },
  { type: "n8n-nodes-base.emailSend", name: "emailSend", displayName: "Send Email", description: "Sends an email using SMTP protocol", category: "Email", icon: "✉️" },
  { type: "n8n-nodes-base.sendGrid", name: "sendGrid", displayName: "SendGrid", description: "Consume SendGrid API", category: "Email", icon: "✉️" },
  { type: "n8n-nodes-base.awsS3", name: "awsS3", displayName: "AwsS3", description: "Sends data to AWS S3", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.azureStorage", name: "azureStorage", displayName: "Azure Storage", description: "Interact with Azure Storage API", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.box", name: "box", displayName: "Box", description: "Consume Box API", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.boxTrigger", name: "boxTrigger", displayName: "Box Trigger", description: "Starts the workflow when Box events occur", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.convertToFile", name: "convertToFile", displayName: "Convert to File", description: "Convert JSON data to binary data", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.dropbox", name: "dropbox", displayName: "Dropbox", description: "Access data on Dropbox", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.extractFromFile", name: "extractFromFile", displayName: "Extract from File", description: "Convert binary data to JSON", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.googleCloudStorage", name: "googleCloudStorage", displayName: "Google Cloud Storage", description: "Use the Google Cloud Storage API", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.googleDrive", name: "googleDrive", displayName: "Google Drive", description: "Access data on Google Drive", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.googleDriveTrigger", name: "googleDriveTrigger", displayName: "Google Drive Trigger", description: "Starts the workflow when Google Drive events occur", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.microsoftOneDrive", name: "microsoftOneDrive", displayName: "Microsoft OneDrive", description: "Consume Microsoft OneDrive API", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.microsoftOneDriveTrigger", name: "microsoftOneDriveTrigger", displayName: "Microsoft OneDrive Trigger", description: "Trigger for Microsoft OneDrive API.", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.microsoftSharePoint", name: "microsoftSharePoint", displayName: "Microsoft SharePoint", description: "Interact with Microsoft SharePoint API", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.nextCloud", name: "nextCloud", displayName: "Nextcloud", description: "Access data on Nextcloud", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.readBinaryFile", name: "readBinaryFile", displayName: "Read Binary File", description: "Reads a binary file from disk", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.readBinaryFiles", name: "readBinaryFiles", displayName: "Read Binary Files", description: "Reads binary files from disk", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.readPDF", name: "readPDF", displayName: "Read PDF", description: "Reads a PDF and extracts its content", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.readWriteFile", name: "readWriteFile", displayName: "Read/Write Files from Disk", description: "Read or write files from the computer that runs n8n", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.s3", name: "s3", displayName: "S3", description: "Sends data to any S3-compatible service", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.ssh", name: "ssh", displayName: "SSH", description: "Execute commands via SSH", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.writeBinaryFile", name: "writeBinaryFile", displayName: "Write Binary File", description: "Writes a binary file to disk", category: "Files", icon: "📂" },
  { type: "n8n-nodes-base.gong", name: "gong", displayName: "Gong", description: "Interact with Gong API", category: "Finance", icon: "💰" },
  { type: "n8n-nodes-base.wise", name: "wise", displayName: "Wise", description: "Consume the Wise API", category: "Finance", icon: "💰" },
  { type: "n8n-nodes-base.wiseTrigger", name: "wiseTrigger", displayName: "Wise Trigger", description: "Handle Wise events via webhooks", category: "Finance", icon: "💰" },
  { type: "n8n-nodes-base.workableTrigger", name: "workableTrigger", displayName: "Workable Trigger", description: "Starts the workflow when Workable events occur", category: "HR", icon: "🧑‍💼" },
  { type: "n8n-nodes-base.graphql", name: "graphql", displayName: "GraphQL", description: "Makes a GraphQL request and returns the received data", category: "HTTP/Web", icon: "🌐" },
  { type: "n8n-nodes-base.httpRequest", name: "httpRequest", displayName: "HTTP Request", description: "Makes an HTTP request and returns the response data", category: "HTTP/Web", icon: "🌐" },
  { type: "n8n-nodes-base.rssFeedReadTrigger", name: "rssFeedReadTrigger", displayName: "RSS Feed Trigger", description: "Starts a workflow when an RSS feed is updated", category: "HTTP/Web", icon: "🌐" },
  { type: "n8n-nodes-base.rssFeedRead", name: "rssFeedRead", displayName: "RSS Read", description: "Reads data from an RSS Feed", category: "HTTP/Web", icon: "🌐" },
  { type: "n8n-nodes-base.homeAssistant", name: "homeAssistant", displayName: "Home Assistant", description: "Consume Home Assistant API", category: "IoT", icon: "🖥️" },
  { type: "n8n-nodes-base.philipsHue", name: "philipsHue", displayName: "Philips Hue", description: "Consume Philips Hue API", category: "IoT", icon: "🖥️" },
  { type: "n8n-nodes-base.bitwarden", name: "bitwarden", displayName: "Bitwarden", description: "Consume the Bitwarden API", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.cortex", name: "cortex", displayName: "Cortex", description: "Apply the Cortex analyzer/responder on the given entity", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.haloPSA", name: "haloPSA", displayName: "HaloPSA", description: "Consume HaloPSA API", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.ldap", name: "ldap", displayName: "Ldap", description: "Interact with LDAP servers", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.misp", name: "misp", displayName: "MISP", description: "Consume the MISP API", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.okta", name: "okta", displayName: "Okta", description: "Use the Okta API", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.securityScorecard", name: "securityScorecard", displayName: "SecurityScorecard", description: "Consume SecurityScorecard API", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.syncroMsp", name: "syncroMsp", displayName: "SyncroMSP", description: "Manage contacts, tickets and more from Syncro MSP", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.theHive", name: "theHive", displayName: "TheHive", description: "Consume TheHive API", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.theHiveProjectTrigger", name: "theHiveProjectTrigger", displayName: "TheHive 5 Trigger", description: "Starts the workflow when TheHive events occur", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.theHiveTrigger", name: "theHiveTrigger", displayName: "TheHive Trigger", description: "Starts the workflow when TheHive events occur", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.urlScanIo", name: "urlScanIo", displayName: "urlscan.io", description: "Provides various utilities for monitoring websites like health checks or screenshots", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.venafiTlsProtectCloud", name: "venafiTlsProtectCloud", displayName: "Venafi TLS Protect Cloud", description: "Consume Venafi TLS Protect Cloud API", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.venafiTlsProtectDatacenter", name: "venafiTlsProtectDatacenter", displayName: "Venafi TLS Protect Datacenter", description: "Consume Venafi TLS Protect Datacenter", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.zammad", name: "zammad", displayName: "Zammad", description: "Consume the Zammad API", category: "IT/Security", icon: "🔒" },
  { type: "n8n-nodes-base.actionNetwork", name: "actionNetwork", displayName: "Action Network", description: "Consume the Action Network API", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.autopilot", name: "autopilot", displayName: "Autopilot", description: "Consume Autopilot API", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.autopilotTrigger", name: "autopilotTrigger", displayName: "Autopilot Trigger", description: "Handle Autopilot events via webhooks", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.convertKit", name: "convertKit", displayName: "ConvertKit", description: "Consume ConvertKit API", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.convertKitTrigger", name: "convertKitTrigger", displayName: "ConvertKit Trigger", description: "Handle ConvertKit events via webhooks", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.customerIo", name: "customerIo", displayName: "Customer.io", description: "Consume Customer.io API", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.customerIoTrigger", name: "customerIoTrigger", displayName: "Customer.io Trigger", description: "Starts the workflow on a Customer.io update (Beta)", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.egoi", name: "egoi", displayName: "E-goi", description: "Consume E-goi API", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.emelia", name: "emelia", displayName: "Emelia", description: "Consume the Emelia API", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.emeliaTrigger", name: "emeliaTrigger", displayName: "Emelia Trigger", description: "Handle Emelia campaign activity events via webhooks", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.iterable", name: "iterable", displayName: "Iterable", description: "Consume Iterable API", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.lemlist", name: "lemlist", displayName: "Lemlist", description: "Consume the Lemlist API", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.lemlistTrigger", name: "lemlistTrigger", displayName: "Lemlist Trigger", description: "Handle Lemlist events via webhooks", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.mailchimp", name: "mailchimp", displayName: "Mailchimp", description: "Consume Mailchimp API", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.mailchimpTrigger", name: "mailchimpTrigger", displayName: "Mailchimp Trigger", description: "Handle Mailchimp events via webhooks", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.mailerLite", name: "mailerLite", displayName: "MailerLite", description: "Consume MailerLite API", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.mailerLiteTrigger", name: "mailerLiteTrigger", displayName: "MailerLite Trigger", description: "Starts the workflow when MailerLite events occur", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.mautic", name: "mautic", displayName: "Mautic", description: "Consume Mautic API", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.mauticTrigger", name: "mauticTrigger", displayName: "Mautic Trigger", description: "Handle Mautic events via webhooks", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.sendy", name: "sendy", displayName: "Sendy", description: "Consume Sendy API", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.tapfiliate", name: "tapfiliate", displayName: "Tapfiliate", description: "Consume Tapfiliate API", category: "Marketing", icon: "📣" },
  { type: "n8n-nodes-base.bannerbear", name: "bannerbear", displayName: "Bannerbear", description: "Consume Bannerbear API", category: "Media", icon: "🎥" },
  { type: "n8n-nodes-base.mindee", name: "mindee", displayName: "Mindee", description: "Consume Mindee API", category: "Media", icon: "🎥" },
  { type: "n8n-nodes-base.quickChart", name: "quickChart", displayName: "QuickChart", description: "Create a chart via QuickChart", category: "Media", icon: "🎥" },
  { type: "n8n-nodes-base.spotify", name: "spotify", displayName: "Spotify", description: "Access public song data via the Spotify API", category: "Media", icon: "🎥" },
  { type: "n8n-nodes-base.youTube", name: "youTube", displayName: "YouTube", description: "Consume YouTube API", category: "Media", icon: "🎥" },
  { type: "n8n-nodes-base.amqp", name: "amqp", displayName: "AMQP Sender", description: "Sends a raw-message via AMQP 1.0, executed once per item", category: "Messaging", icon: "📨" },
  { type: "n8n-nodes-base.amqpTrigger", name: "amqpTrigger", displayName: "AMQP Trigger", description: "Listens to AMQP 1.0 messages", category: "Messaging", icon: "📨" },
  { type: "n8n-nodes-base.kafka", name: "kafka", displayName: "Kafka", description: "Sends messages to a Kafka topic", category: "Messaging", icon: "📨" },
  { type: "n8n-nodes-base.kafkaTrigger", name: "kafkaTrigger", displayName: "Kafka Trigger", description: "Consume messages from a Kafka topic", category: "Messaging", icon: "📨" },
  { type: "n8n-nodes-base.mqtt", name: "mqtt", displayName: "MQTT", description: "Push messages to MQTT", category: "Messaging", icon: "📨" },
  { type: "n8n-nodes-base.mqttTrigger", name: "mqttTrigger", displayName: "MQTT Trigger", description: "Listens to MQTT events", category: "Messaging", icon: "📨" },
  { type: "n8n-nodes-base.rabbitmq", name: "rabbitmq", displayName: "RabbitMQ", description: "Sends messages to a RabbitMQ topic", category: "Messaging", icon: "📨" },
  { type: "n8n-nodes-base.rabbitmqTrigger", name: "rabbitmqTrigger", displayName: "RabbitMQ Trigger", description: "Listens to RabbitMQ messages", category: "Messaging", icon: "📨" },
  { type: "n8n-nodes-base.adalo", name: "adalo", displayName: "Adalo", description: "Consume Adalo API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.airtop", name: "airtop", displayName: "Airtop", description: "Scrape and control any site with Airtop", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.apiTemplateIo", name: "apiTemplateIo", displayName: "APITemplate.io", description: "Consume the APITemplate.io API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.Blur", name: "Blur", displayName: "Background Color", description: "Adds a blur to the image and so makes it less sharp", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.beeminder", name: "beeminder", displayName: "Beeminder", description: "Consume Beeminder API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.bitly", name: "bitly", displayName: "Bitly", description: "Consume Bitly API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.Brandfetch", name: "Brandfetch", displayName: "Brandfetch", description: "Consume Brandfetch API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.sendInBlueApi", name: "sendInBlueApi", displayName: "Brevo Trigger", description: "Starts the workflow when Brevo events occur", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.clearbit", name: "clearbit", displayName: "Clearbit", description: "Consume Clearbit API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.cockpit", name: "cockpit", displayName: "Cockpit", description: "Consume Cockpit API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.coinGecko", name: "coinGecko", displayName: "CoinGecko", description: "Consume CoinGecko API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.currents", name: "currents", displayName: "Currents", description: "Interact with the Currents API for test orchestration and analytics", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.currentsTrigger", name: "currentsTrigger", displayName: "Currents Trigger", description: "Starts the workflow when Currents events occur", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.Jay Gatsby", name: "Jay Gatsby", displayName: "Customer Datastore (n8n training)", description: "Dummy node used for n8n training", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.deepL", name: "deepL", displayName: "DeepL", description: "Translate data using DeepL", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.dhl", name: "dhl", displayName: "DHL", description: "Consume DHL API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.documentId", name: "documentId", displayName: "Document", description: "Starts the workflow when Google Sheets events occur", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.e2eTest", name: "e2eTest", displayName: "E2E Test", description: "Dummy node used for e2e testing", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.e2eTestPollingTrigger", name: "e2eTestPollingTrigger", displayName: "E2E Test Polling Trigger", description: "Dummy polling trigger for e2e testing", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.elasticSecurity", name: "elasticSecurity", displayName: "Elastic Security", description: "Consume the Elastic Security API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.executeCommand", name: "executeCommand", displayName: "Execute Command", description: "Executes a command on the host", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.executionData", name: "executionData", displayName: "Execution Data", description: "Add execution data for search", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.extractionValues", name: "extractionValues", displayName: "Extraction Values", description: "The key under which the extracted value should be saved", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.facebookGraphApi", name: "facebookGraphApi", displayName: "Facebook Graph API", description: "Interacts with Facebook using the Graph API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.filemaker", name: "filemaker", displayName: "FileMaker", description: "Retrieve data from the FileMaker data API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.flow", name: "flow", displayName: "Flow", description: "Consume Flow API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.flowTrigger", name: "flowTrigger", displayName: "Flow Trigger", description: "Handle Flow events via webhooks", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.setInputsNotice", name: "setInputsNotice", displayName: "For adding columns from your dataset to the evaluation results. Anything you add here will be displayed in the ‘evaluations’ tab, not on the Google Sheet or Data table.", description: "The expected output defined in your evaluation dataset, used as ground truth", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.formIoTrigger", name: "formIoTrigger", displayName: "Form.io Trigger", description: "Handle form.io events via webhooks", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.formstackTrigger", name: "formstackTrigger", displayName: "Formstack Trigger", description: "Starts the workflow on a Formstack form submission.", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.getResponse", name: "getResponse", displayName: "GetResponse", description: "Consume GetResponse API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.getResponseTrigger", name: "getResponseTrigger", displayName: "GetResponse Trigger", description: "Starts the workflow when GetResponse events occur", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.Comment", name: "Comment", displayName: "GitLab Trigger", description: "Triggered when a new comment is made on commits, merge requests, issues, and code snippets", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.googleFirebaseCloudFirestore", name: "googleFirebaseCloudFirestore", displayName: "Google Cloud Firestore", description: "Interact with Google Firebase - Cloud Firestore API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.googleFirebaseRealtimeDatabase", name: "googleFirebaseRealtimeDatabase", displayName: "Google Cloud Realtime Database", description: "Interact with Google Firebase - Realtime Database API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.hackerNews", name: "hackerNews", displayName: "Hacker News", description: "Consume Hacker News API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.iCal", name: "iCal", displayName: "iCalendar", description: "Create iCalendar file", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.jotFormTrigger", name: "jotFormTrigger", displayName: "Jotform Trigger", description: "Handle Jotform events via webhooks", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.koBoToolbox", name: "koBoToolbox", displayName: "KoBoToolbox", description: "Work with KoBoToolbox forms and submissions", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.koBoToolboxTrigger", name: "koBoToolboxTrigger", displayName: "KoBoToolbox Trigger", description: "Process KoBoToolbox submissions", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.limitWaitTime", name: "limitWaitTime", displayName: "Limit Wait Time", description: "Whether to limit the time this node should wait for a user response before execution resumes", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.lingvaNex", name: "lingvaNex", displayName: "LingvaNex", description: "Consume LingvaNex API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.linkedIn", name: "linkedIn", displayName: "LinkedIn", description: "Consume LinkedIn API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.loneScale", name: "loneScale", displayName: "LoneScale", description: "Enrich and source contacts, search companies, and manage lists", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.loneScaleTrigger", name: "loneScaleTrigger", displayName: "LoneScale Trigger", description: "Trigger LoneScale Workflow", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.mailcheck", name: "mailcheck", displayName: "Mailcheck", description: "Consume Mailcheck API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.mailjetTrigger", name: "mailjetTrigger", displayName: "Mailjet Trigger", description: "Handle Mailjet events via webhooks", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.marketstack", name: "marketstack", displayName: "Marketstack", description: "Consume Marketstack API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.messageBird", name: "messageBird", displayName: "MessageBird", description: "Sends SMS via MessageBird", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.microsoftDynamicsCrm", name: "microsoftDynamicsCrm", displayName: "Microsoft Dynamics CRM", description: "Consume Microsoft Dynamics CRM API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.microsoftEntra", name: "microsoftEntra", displayName: "Microsoft Entra ID", description: "Interact with Microsoft Entra ID API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.microsoftGraphSecurity", name: "microsoftGraphSecurity", displayName: "Microsoft Graph Security", description: "Consume the Microsoft Graph Security API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.microsoftToDo", name: "microsoftToDo", displayName: "Microsoft To Do", description: "Consume Microsoft To Do API.", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.nasa", name: "nasa", displayName: "NASA", description: "Retrieve data from the NASA API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.citrixAdc", name: "citrixAdc", displayName: "Netscaler ADC", description: "Consume Netscaler ADC API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.oneSimpleApi", name: "oneSimpleApi", displayName: "One Simple API", description: "A toolbox of no-code utilities", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.onfleet", name: "onfleet", displayName: "Onfleet", description: "Consume Onfleet API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.onfleetTrigger", name: "onfleetTrigger", displayName: "Onfleet Trigger", description: "Starts the workflow when Onfleet events occur", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.openThesaurus", name: "openThesaurus", displayName: "OpenThesaurus", description: "Get synonmns for German words using the OpenThesaurus API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.openWeatherMap", name: "openWeatherMap", displayName: "OpenWeatherMap", description: "Gets current and future weather information", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.orbit", name: "orbit", displayName: "Orbit", description: "Consume Orbit API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.oura", name: "oura", displayName: "Oura", description: "Consume Oura API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.peekalink", name: "peekalink", displayName: "Peekalink", description: "Consume the Peekalink API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.phantombuster", name: "phantombuster", displayName: "Phantombuster", description: "Consume Phantombuster API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.Activity", name: "Activity", displayName: "Pipedrive Trigger", description: "Starts the workflow when Pipedrive events occur", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.postBin", name: "postBin", displayName: "PostBin", description: "Consume PostBin API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.profitWell", name: "profitWell", displayName: "ProfitWell", description: "Consume ProfitWell API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.pushbullet", name: "pushbullet", displayName: "Pushbullet", description: "Consume Pushbullet API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.pushcut", name: "pushcut", displayName: "Pushcut", description: "Consume Pushcut API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.pushcutTrigger", name: "pushcutTrigger", displayName: "Pushcut Trigger", description: "Starts the workflow when Pushcut events occur", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.pushover", name: "pushover", displayName: "Pushover", description: "Consume Pushover API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.quickbase", name: "quickbase", displayName: "Quick Base", description: "Integrate with the Quick Base RESTful API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.raindrop", name: "raindrop", displayName: "Raindrop", description: "Consume the Raindrop API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.respondWith", name: "respondWith", displayName: "Respond With", description: "Respond with all input JSON items", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.signl4", name: "signl4", displayName: "SIGNL4", description: "Consume SIGNL4 API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.splunk", name: "splunk", displayName: "Splunk", description: "Consume the Splunk Enterprise API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.strava", name: "strava", displayName: "Strava", description: "Consume Strava API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.stravaTrigger", name: "stravaTrigger", displayName: "Strava Trigger", description: "Starts the workflow when Strava events occur", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.surveyMonkeyTrigger", name: "surveyMonkeyTrigger", displayName: "SurveyMonkey Trigger", description: "Starts the workflow when Survey Monkey events occur", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.timeout", name: "timeout", displayName: "Timeout", description: "Connection timeout in milliseconds", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.typeformTrigger", name: "typeformTrigger", displayName: "Typeform Trigger", description: "Starts the workflow on a Typeform form submission", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.unleashedSoftware", name: "unleashedSoftware", displayName: "Unleashed Software", description: "Consume Unleashed Software API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.uproc", name: "uproc", displayName: "uProc", description: "Consume uProc API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.uptimeRobot", name: "uptimeRobot", displayName: "UptimeRobot", description: "Consume UptimeRobot API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.venafiTlsProtectCloudTrigger", name: "venafiTlsProtectCloudTrigger", displayName: "Venafi TLS Protect Cloud Trigger", description: "Starts the workflow when Venafi events occur", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.venafiTlsProtectDatacenterTrigger", name: "venafiTlsProtectDatacenterTrigger", displayName: "Venafi TLS Protect Datacenter Trigger", description: "Starts the workflow when Venafi events occur", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.vero", name: "vero", displayName: "Vero", description: "Consume Vero API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.amount", name: "amount", displayName: "Wait Amount", description: "The time to wait", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.wufooTrigger", name: "wufooTrigger", displayName: "Wufoo Trigger", description: "Handle Wufoo events via webhooks", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.yourls", name: "yourls", displayName: "Yourls", description: "Consume Yourls API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.zoom", name: "zoom", displayName: "Zoom", description: "Consume Zoom API", category: "Other", icon: "📦" },
  { type: "n8n-nodes-base.bubble", name: "bubble", displayName: "Bubble", description: "Consume the Bubble Data API", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.eventbriteTrigger", name: "eventbriteTrigger", displayName: "Eventbrite Trigger", description: "Handle Eventbrite events via webhooks", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.figmaTrigger", name: "figmaTrigger", displayName: "Figma Trigger (Beta)", description: "Starts the workflow when Figma events occur", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.freshdesk", name: "freshdesk", displayName: "Freshdesk", description: "Consume Freshdesk API", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.freshservice", name: "freshservice", displayName: "Freshservice", description: "Consume the Freshservice API", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.googleBooks", name: "googleBooks", displayName: "Google Books", description: "Read data from Google Books", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.googleBusinessProfile", name: "googleBusinessProfile", displayName: "Google Business Profile", description: "Consume Google Business Profile API", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.googleBusinessProfileTrigger", name: "googleBusinessProfileTrigger", displayName: "Google Business Profile Trigger", description: "Fetches reviews from Google Business Profile and starts the workflow on specified polling intervals.", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.googleCloudNaturalLanguage", name: "googleCloudNaturalLanguage", displayName: "Google Cloud Natural Language", description: "Consume Google Cloud Natural Language API", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.googleContacts", name: "googleContacts", displayName: "Google Contacts", description: "Consume Google Contacts API", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.googlePerspective", name: "googlePerspective", displayName: "Google Perspective", description: "Consume Google Perspective API", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.googleTasks", name: "googleTasks", displayName: "Google Tasks", description: "Consume Google Tasks API", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.googleTranslate", name: "googleTranslate", displayName: "Google Translate", description: "Translate data using Google Translate", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.gSuiteAdmin", name: "gSuiteAdmin", displayName: "Google Workspace Admin", description: "Consume Google Workspace Admin API", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.goToWebinar", name: "goToWebinar", displayName: "GoToWebinar", description: "Consume the GoToWebinar API", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.helpScout", name: "helpScout", displayName: "Help Scout", description: "Consume Help Scout API", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.helpScoutTrigger", name: "helpScoutTrigger", displayName: "Help Scout Trigger", description: "Starts the workflow when Help Scout events occur", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.webflow", name: "webflow", displayName: "Webflow", description: "Consume the Webflow API", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.webflowTrigger", name: "webflowTrigger", displayName: "Webflow Trigger", description: "Handle Webflow events via webhooks", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.zendesk", name: "zendesk", displayName: "Zendesk", description: "Consume Zendesk API", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.zendeskTrigger", name: "zendeskTrigger", displayName: "Zendesk Trigger", description: "Handle Zendesk events via webhooks", category: "Productivity", icon: "📁" },
  { type: "n8n-nodes-base.asana", name: "asana", displayName: "Asana", description: "Consume Asana REST API", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.asanaTrigger", name: "asanaTrigger", displayName: "Asana Trigger", description: "Starts the workflow when Asana events occur.", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.clickUp", name: "clickUp", displayName: "ClickUp", description: "Consume ClickUp API (Beta)", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.clickUpTrigger", name: "clickUpTrigger", displayName: "ClickUp Trigger", description: "Handle ClickUp events via webhooks (Beta)", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.clockify", name: "clockify", displayName: "Clockify", description: "Consume Clockify REST API", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.clockifyTrigger", name: "clockifyTrigger", displayName: "Clockify Trigger", description: "Listens to Clockify events", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.coda", name: "coda", displayName: "Coda", description: "Consume Coda API", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.harvest", name: "harvest", displayName: "Harvest", description: "Access data on Harvest", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.jira", name: "jira", displayName: "Jira Software", description: "Consume Jira Software API", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.jiraTrigger", name: "jiraTrigger", displayName: "Jira Trigger", description: "Starts the workflow when Jira events occur", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.linear", name: "linear", displayName: "Linear", description: "Consume Linear API", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.linearTrigger", name: "linearTrigger", displayName: "Linear Trigger", description: "Starts the workflow when Linear events occur", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.mondayCom", name: "mondayCom", displayName: "Monday.com", description: "Consume Monday.com API", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.notion", name: "notion", displayName: "Notion", description: "Consume Notion API", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.notionTrigger", name: "notionTrigger", displayName: "Notion Trigger", description: "Starts the workflow when Notion events occur", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.taiga", name: "taiga", displayName: "Taiga", description: "Consume Taiga API", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.taigaTrigger", name: "taigaTrigger", displayName: "Taiga Trigger", description: "Handle Taiga events via webhook", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.todoist", name: "todoist", displayName: "Todoist", description: "Consume Todoist API", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.togglTrigger", name: "togglTrigger", displayName: "Toggl Trigger", description: "Starts the workflow when Toggl events occur", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.trello", name: "trello", displayName: "Trello", description: "Create, change and delete boards and cards", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.trelloTrigger", name: "trelloTrigger", displayName: "Trello Trigger", description: "Starts the workflow when Trello events occur", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.wekan", name: "wekan", displayName: "Wekan", description: "Consume Wekan API", category: "Project Management", icon: "📋" },
  { type: "n8n-nodes-base.mocean", name: "mocean", displayName: "Mocean", description: "Send SMS and voice messages via Mocean", category: "SMS/Phone", icon: "📱" },
  { type: "n8n-nodes-base.msg91", name: "msg91", displayName: "MSG91", description: "Sends transactional SMS via MSG91", category: "SMS/Phone", icon: "📱" },
  { type: "n8n-nodes-base.plivo", name: "plivo", displayName: "Plivo", description: "Send SMS/MMS messages or make phone calls", category: "SMS/Phone", icon: "📱" },
  { type: "n8n-nodes-base.sms77", name: "sms77", displayName: "seven", description: "Send SMS and make text-to-speech calls", category: "SMS/Phone", icon: "📱" },
  { type: "n8n-nodes-base.twilio", name: "twilio", displayName: "Twilio", description: "Send SMS and WhatsApp messages or make phone calls", category: "SMS/Phone", icon: "📱" },
  { type: "n8n-nodes-base.twilioTrigger", name: "twilioTrigger", displayName: "Twilio Trigger", description: "Starts the workflow on a Twilio update", category: "SMS/Phone", icon: "📱" },
  { type: "n8n-nodes-base.vonage", name: "vonage", displayName: "Vonage", description: "Consume Vonage API", category: "SMS/Phone", icon: "📱" },
  { type: "n8n-nodes-base.discourse", name: "discourse", displayName: "Discourse", description: "Consume Discourse API", category: "Social Media", icon: "👥" },
  { type: "n8n-nodes-base.disqus", name: "disqus", displayName: "Disqus", description: "Access data on Disqus", category: "Social Media", icon: "👥" },
  { type: "n8n-nodes-base.facebookLeadAdsTrigger", name: "facebookLeadAdsTrigger", displayName: "Facebook Lead Ads Trigger", description: "Handle Facebook Lead Ads events via webhooks", category: "Social Media", icon: "👥" },
  { type: "n8n-nodes-base.facebookTrigger", name: "facebookTrigger", displayName: "Facebook Trigger", description: "Starts the workflow when Facebook events occur", category: "Social Media", icon: "👥" },
  { type: "n8n-nodes-base.medium", name: "medium", displayName: "Medium", description: "Consume Medium API", category: "Social Media", icon: "👥" },
  { type: "n8n-nodes-base.reddit", name: "reddit", displayName: "Reddit", description: "Consume the Reddit API", category: "Social Media", icon: "👥" },
  { type: "n8n-nodes-base.whatsApp", name: "whatsApp", displayName: "WhatsApp Business Cloud", description: "Access WhatsApp API", category: "Social Media", icon: "👥" },
  { type: "n8n-nodes-base.whatsAppTrigger", name: "whatsAppTrigger", displayName: "WhatsApp Trigger", description: "Handle WhatsApp events via webhooks", category: "Social Media", icon: "👥" },
  { type: "n8n-nodes-base.twitter", name: "twitter", displayName: "X (Formerly Twitter)", description: "Consume the X API", category: "Social Media", icon: "👥" },
  { type: "n8n-nodes-base.cron", name: "cron", displayName: "Cron", description: "Triggers the workflow at a specific time", category: "Triggers", icon: "⚡" },
  { type: "n8n-nodes-base.errorTrigger", name: "errorTrigger", displayName: "Error Trigger", description: "Triggers the workflow when another workflow has an error", category: "Triggers", icon: "⚡" },
  { type: "n8n-nodes-base.executeWorkflow", name: "executeWorkflow", displayName: "Execute Sub-workflow", description: "Execute another workflow", category: "Triggers", icon: "⚡" },
  { type: "n8n-nodes-base.executeWorkflowTrigger", name: "executeWorkflowTrigger", displayName: "Execute Workflow Trigger", description: "Helpers for calling other n8n workflows. Used for designing modular, microservice-like workflows.", category: "Triggers", icon: "⚡" },
  { type: "n8n-nodes-base.interval", name: "interval", displayName: "Interval", description: "Triggers the workflow in a given interval", category: "Triggers", icon: "⚡" },
  { type: "n8n-nodes-base.localFileTrigger", name: "localFileTrigger", displayName: "Local File Trigger", description: "Triggers a workflow on file system changes", category: "Triggers", icon: "⚡" },
  { type: "n8n-nodes-base.manualTrigger", name: "manualTrigger", displayName: "Manual Trigger", description: "Runs the flow on clicking a button in n8n", category: "Triggers", icon: "⚡" },
  { type: "n8n-nodes-base.scheduleTrigger", name: "scheduleTrigger", displayName: "Schedule Trigger", description: "Triggers the workflow on a given schedule", category: "Triggers", icon: "⚡" },
  { type: "n8n-nodes-base.simulateTrigger", name: "simulateTrigger", displayName: "Simulate Trigger", description: "Simulate a trigger node", category: "Triggers", icon: "⚡" },
  { type: "n8n-nodes-base.sseTrigger", name: "sseTrigger", displayName: "SSE Trigger", description: "Triggers the workflow when Server-Sent Events occur", category: "Triggers", icon: "⚡" },
  { type: "n8n-nodes-base.webhook", name: "webhook", displayName: "Webhook", description: "Starts the workflow when a webhook is called", category: "Triggers", icon: "⚡" },
  { type: "n8n-nodes-base.workflowTrigger", name: "workflowTrigger", displayName: "Workflow Trigger", description: "Triggers based on various lifecycle events, like when a workflow is activated", category: "Triggers", icon: "⚡" },
];

export function getNodesByCategory(category: string): N8nNodeType[] {
  return N8N_NODE_TYPES.filter(n => n.category === category);
}

export function getNodeCategories(): string[] {
  return [...new Set(N8N_NODE_TYPES.map(n => n.category))].sort();
}
